from dataclasses import dataclass
from Options import FreeText, OptionDict, OptionSet, StartInventoryPool, Choice, Range, PerGameCommonOptions, Toggle, OptionDict, OptionError
from schema import Optional, Schema, And
from typing import Any
from .Items import InstrumentItems

# Maximum number of songs available.

# Supported instrument names
VALID_INSTRUMENTS = {item.name for item in InstrumentItems}

# Completion requirement names (from CompletionReq enum)
VALID_COMPLETION_REQS = {
    "Clear", "OneStar", "TwoStar", "ThreeStar",
    "FourStar", "FiveStar", "GoldStar", "FullCombo"
}

# Difficulty names (from SupportedDifficulty enum)
VALID_DIFFICULTY_NAMES = {
    "Easy",    # 1
    "Medium",  # 2
    "Hard",    # 3
    "Expert"   # 4
}

# Song Check Options
class SongList(FreeText):
    """
    Accepts either:
    1. The filename of your song list json file (generated by the YAML Creation tool) that must be placed in the 
       'YAYARG Song Data' folder within the Archipelago directory of the person generating the seed
    2. A song data hash string exported from the YAML Creation tool
    
    WARNING: Hash strings cannot use weighted option syntax. Replace 'null' with the hash string in quotes.
    Example: song_list: "your_hash_string_here"
    """
    display_name = "Song List"
    default = None
    
class SongExclusions(OptionSet):
    """
    A list of songs that will be completely excluded from your seed.

    Songs must be specified by their song hash, which can be obtained
    from the YAML Generator.

    Example::
        [song_hash_5, song_hash_6, song_hash_7]
    """
    display_name = "Global Song Exclusions"


class SongExclusionPerPool(OptionDict):
    """
    A mapping of songs to the specific pools they should be excluded from.

    Songs must be specified by their song hash, which can be obtained
    from the YAML Generator.

    Example::
        song_hash_3: ['Guitar Pool Name', 'Bass Pool Name']
        song_hash_4: ['Drum Pool Name']
    """
    display_name = "Song Pool Exclusions"
    schema = Schema({
        str: list[str]
    })
    default = {}


class SongInclusionsPerPool(OptionDict):
    """
    A mapping of songs to the pools they are required to appear in.

    Each listed song will always appear in at least one of the specified pools.

    Songs must be specified by their song hash, which can be obtained
    from the YAML Generator.
    
    Example::
        song_hash_3: ['Guitar Pool Name', 'Bass Pool Name']
        song_hash_4: ['Drum Pool Name']
    """
    display_name = "Song Pool Inclusions"
    schema = Schema({
        str: list[str]
    })
    default = {}


class GoalSongPoolPlando(FreeText):
    """
    Forces the goal song into the given pool
    """
    display_name = "Goal Pool Plando"
    default = ""

class GoalSongSongPlando(FreeText):
    """
    Forces the goal song to be the given song
    
    The song must be entered by the song hash which can be obtained from the YAML Generator
    """
    display_name = "Goal Song Plando"
    default = ""

class SongPools(OptionDict):
    """
    Define custom song pools for the randomizer. Each pool specifies which songs are available based on 
    instrument and difficulty requirements, and how many songs from that pool should be checkable locations.
    
    Each song pool must have a unique name and specify:
    - instrument: The instrument this pool is for (see supported instruments below)
    - amount_in_pool: Number of songs from this pool to include
    - min_difficulty: Minimum difficulty tier (0 or higher)
    - max_difficulty: Maximum difficulty tier (0 or higher)
    - completion_requirements: Settings for what counts as completing a song
    
    **Supported Instruments:**
    - FiveFretGuitar: Standard 5-button guitar
    - FiveFretBass: Standard 5-button bass
    - FourLaneDrums: 4-lane drums (Rock Band style)
    - ProDrums: Pro drums with cymbals
    - FiveLaneDrums: 5-lane drums (Guitar Hero style)
    - Keys: Keyboard/keys
    - ProKeys: Pro keys with multiple lanes
    - Vocals: Lead vocals
    - Harmony: Harmony vocals

    **Completion Requirements:**
    - reward1_req: Score requirement for the standard reward
      - Clear: Just complete the song
      - OneStar: Achieve 1 star
      - TwoStar: Achieve 2 stars
      - ThreeStar: Achieve 3 stars
      - FourStar: Achieve 4 stars
      - FiveStar: Achieve 5 stars
      - GoldStar: Achieve gold star rating
      - FullCombo: Complete without missing any notes or breaking combo
    - reward1_diff: The difficulty you must complete the song at for the standard reward
      - Easy
      - Medium
      - Hard
      - Expert
    - reward2_req: Requirement for the extra reward if one exists (same options as reward1_req)
    - reward2_diff: Difficulty tier for the extra reward if one exists (same options as reward1_diff)
    """
    display_name = "Song Pools"
    
    # Default pool: Standard guitar with moderate difficulty
    default = {
        "Guitar": {
            "instrument": "FiveFretGuitar",
            "amount_in_pool": 40,
            "min_difficulty": 3,
            "max_difficulty": 5,
            "completion_requirements": {
                "reward1_req": "Clear",
                "reward1_diff": "Expert",
                "reward2_req": "ThreeStar",
                "reward2_diff": "Expert"
            }
        }
    }
    
    schema = Schema({
        str: {  # Pool name (must be unique)
            "instrument": And(str, lambda s: s in VALID_INSTRUMENTS),
            "amount_in_pool": And(int, lambda n: n >= 0),
            "min_difficulty": And(int, lambda n: n >= 0),
            "max_difficulty": And(int, lambda n: n >= 0),
            "completion_requirements": {
                "reward1_req": And(str, lambda s: s in VALID_COMPLETION_REQS),
                "reward1_diff": And(str, lambda s: s in VALID_DIFFICULTY_NAMES),
                "reward2_req": And(str, lambda s: s in VALID_COMPLETION_REQS),
                "reward2_diff": And(str, lambda s: s in VALID_DIFFICULTY_NAMES)
            }
        }
    })
    
    def __init__(self, value: dict[str, Any]):
        # Validate that min_difficulty <= max_difficulty for each pool
        for pool_name, pool_data in value.items():
            min_diff = pool_data.get("min_difficulty", 0)
            max_diff = pool_data.get("max_difficulty", 999)
            if min_diff > max_diff:
                raise OptionError(
                    f"Song pool '{pool_name}': min_difficulty ({min_diff}) cannot be greater than "
                    f"max_difficulty ({max_diff})"
                )
        
        self.value = value
    
    @classmethod
    def from_any(cls, data: dict[str, Any]) -> "SongPools":
        if type(data) == dict:
            return cls(data)
        else:
            raise NotImplementedError(f"Cannot convert from non-dictionary, got {type(data)}")
    
class SongCheckExtra(Range):
    """
    Determines what percentage of song locations will award an extra item when completed. This includes starting songs.
    """
    display_name = "Extra Check Percentage"
    range_start = 0
    range_end = 100
    default = 100

class SongPackAmount(Range):
    """
    Determines how many songs an unlock item will unlock at once.
    If this is set to 1, you will find individual songs in the pool.
    Otherwise, you will find "Song Pack" items that unlock multiple songs at once.
    """
    display_name = "Song Pack Amount"
    range_start = 1
    range_end = 999
    default = 1

class ResuseSongsAcrossInstruments(Toggle):
    """
    If enabled, the same song can appear once for each instrument.
    If disabled, each song can only appear once total across all pools.
    """
    display_name = "Reuse Songs Across Instruments"

class InstrumentShuffle(Toggle):
    """
    You will need to collect an instruments item before you can play songs requiring that instrument.
    You start with one random instrument unlocked.
    Requires at least two song pools with different instruments.
    """
    display_name = "Instrument Shuffle"

# Victory and Fame Settings

class GoalSongNeedsItem(Toggle):
    """
    Does your goal songs song item need to be found before it can be completed
    """
    display_name = "Goal Song Needs Item"

class SetlistCompletionNeeded(Range):
    """
    What percentage of your total songs should be completed to unlock your goal song.
    """
    display_name = "Setlist Percentage"
    range_start = 0
    range_end = 100
    default = 80
    
class FamePointsNeeded(Range):
    """
    What percentage of fame points in the pool should be required to unlock your goal song.
    """
    display_name = "Fame Point Percentage"
    range_start = 0
    range_end = 100
    default = 80
    
class FamePointsAdded(Range):
    """If goal is set to require fame points, add this many to the pool"""
    display_name = "Fame Point Amount"
    range_start = 0
    range_end = 999
    default = 30

# Starting Songs Option
class StartingSongs(Range):
    """Sets the number of songs you start with in your setlist."""
    display_name = "Starting Songs"
    range_start = 1
    range_end = 999
    default = 3

# Filler Option
class StarPowerItem(Range):
    """
    Specifies the weight of the Star Power filler item.
    This item adds 1/4 of a Star Power bar when received.

    If all filler/trap items are set to a weight of zero, this value will be forced to 1
    """
    display_name = "Star Power Item Filler Weight"
    range_start = 0
    range_end = 999
    default = 5

class SwapSongRandom(Range):
    """
    Specifies the weight of the Swap Song (Random) filler item.
    This item lets you swap one of your songs with a randomly selected new song.
    """
    display_name = "Swap Song Random Filler Weight"
    range_start = 0
    range_end = 999
    default = 5

class SwapSongChoice(Range):
    """
    Specifies the weight of the Swap Song (Choice) filler item.
    This item lets you swap one of your songs with a new one of your choice.
    """
    display_name = "Swap Song Choice Filler Weight"
    range_start = 0
    range_end = 999
    default = 3

class LowerDifficulty(Range):
    """
    Specifies the weight of the Lower Difficulty filler item.
    This item lets you Lower the instrument difficulty or score requirement for a song of your choice.
    """
    display_name = "Lower Difficulty Filler Weight"
    range_start = 0
    range_end = 999
    default = 0

class RestartTrap(Range):
    """
    Specifies the weight of the Restart Trap filler item.
    Recieving this item during a song will cause the song to immediately exit to the menu.
    """
    display_name = "Restart Trap Filler Weight"
    range_start = 0
    range_end = 999
    default = 0

class RockMeterTrap(Range):
    """
    Specifies the weight of the Rock Meter Trap filler item.
    Recieving this item during a song will drain your rock meter by 1/4th.
    """
    display_name = "Rock Meter Trap Filler Weight"
    range_start = 0
    range_end = 999
    default = 1

# DeathLink Option
class YargDeathLink(Choice):
    """
    Failing a song will send a DeathLink to others. 
    If you receive a DeathLink, you will instantly fail your current song. 

    Death link will trigger if you fail a song or if you fail to meet the requirements for the song location check after completing it.

    Modes:
    Instant Fail: Recieving a DeathLink will cause you to instantly fail the song you are currently playing.
    Rock Meter: Recieving a DeathLink will cause the Rock Meter to decrease low enough that missing a single note will cause you to fail.
        -Rock Meter is not supported in Yarg Stable. If selected when using that version, Instant Fail will be used instead.

    This setting can be modfied mid-game at any time in the client.
    """
    display_name = "Death Link"
    option_disabled = 0
    option_rock_meter = 1
    option_instant_fail = 2
    default = 0


# EnergyLink Option
class YargEnergyLink(Choice):
    """
    Completing songs adds energy to the Energy Link pool based on your total score.
    The conversion rate scales from 1:20,000 (0% complete) to 1:1,000,000 (100% complete).

    Modes:
    - Check Song: Only songs that send item checks contribute energy and only once when the location is checked.
    - Other Song: Only songs without item checks contribute energy.
    - Any Song: All completed songs contribute energy.
    """
    display_name = "Energy Link"
    option_disabled = 0
    option_check_song = 1
    option_other_song = 2
    option_any_song = 3
    default = 0

@dataclass
class YargOptions(PerGameCommonOptions):
    songList: SongList
    song_pools: SongPools
    song_exclusion_list: SongExclusions
    exclusions_per_pool: SongExclusionPerPool
    inclusions_per_pool: SongInclusionsPerPool
    goal_pool_plando: GoalSongPoolPlando
    goal_song_plando: GoalSongSongPlando
    song_check_extra: SongCheckExtra
    song_pack_size: SongPackAmount
    instrument_shuffle: InstrumentShuffle
    reuse_songs: ResuseSongsAcrossInstruments
    starting_songs: StartingSongs
    goal_song_item_needed: GoalSongNeedsItem
    setlist_needed: SetlistCompletionNeeded
    fame_point_needed: FamePointsNeeded
    fame_point_amount: FamePointsAdded
    star_power: StarPowerItem
    swap_song_random: SwapSongRandom
    swap_song_choice: SwapSongChoice
    lower_difficulty: LowerDifficulty
    restart_trap: RestartTrap
    rock_meter_trap: RockMeterTrap
    death_link: YargDeathLink
    energy_link: YargEnergyLink
    start_inventory_from_pool: StartInventoryPool
